on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: OQuaRE-metrics-test
    steps:
      # To use this repository's private action
      # You need to check out the repo
      - uses: actions/checkout@v2
      # Configuration
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: OQuaRE testing
        uses: Emdien/oquare-metrics@v1.0.1 
        with:
          ontology-files: ontologias/obi.owl
          contents-folder: metricas-ontologias

